---
# General
ibe_example_product_account_email: "admin.aws+ib-example.example-product@go-atomic.io"
ibe_management_account_email: "admin.aws+ib-example.management@go-atomic.io"
ibe_development_molybdenum_account_email: "admin.aws+ib-example.development.molybdenum@go-atomic.io"
ibe_production_holmium_account_email: "admin.aws+ib-example.production.holmium@go-atomic.io"

# State
organization_state_bucket_name: "%{hiera('storage_bucket_name')}"
organization_state_bucket_region: "%{hiera('region')}"
organization_state_key: "organization/deployment-state/default.tfstate"
organization_state_bucket_is_encrypted: "true"
