---
# General
ibe_parent_account_email: "admin.aws+ibe.parent@go-atomic.io"
ibe_management_account_email: "admin.aws+ibe.management@go-atomic.io"
ibe_development_molybdenum_account_email: "admin.aws+ibe.development.molybdenum@go-atomic.io"
ibe_production_holmium_account_email: "admin.aws+ibe.production.holmium@go-atomic.io"

# State
organization_state_bucket_name: "%{hiera('storage_bucket_name')}"
organization_state_bucket_region: "%{hiera('region')}"
organization_state_key: "organization/deployment-state/default.tfstate"
organization_state_bucket_is_encrypted: "true"
