version: 2.1

jobs:
  provision:
    docker:
      - image: ruby:2.7.4
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/install-aws-cli.sh
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/steps/provision-organisation.sh

workflows:
  version: 2
  pipeline:
    jobs:
      - provision:
          filters:
            branches:
              only: master
