---
ci_account_id: "%{hiera('ibe_management_account_id')}"

ci_deployment_identifier: "%{ci_deployment_group}-%{ci_deployment_type}-%{ci_deployment_label}"

ci_storage_bucket_name: "%{ci_deployment_group}-%{hiera('component')}-%{hiera('ci_deployment_identifier')}"
ci_storage_bucket_region: "%{hiera('region')}"
ci_storage_bucket_encryption: "AES256"

concourse_url: "https://ci-server.management.go-atomic.io"
concourse_team: "atomic"

image_repository_base_url: "%{hiera('ibe_management_account_id')}.dkr.ecr.%{hiera('region')}.amazonaws.com"

infra_builder_image_repository_name: "%{ci_deployment_group}/infra-builder"
infra_builder_image_repository_url: "%{hiera('image_repository_base_url')}/%{hiera('infra_builder_image_repository_name')}"
