---
# General
region: "eu-west-2"

development_group: "ibe"

component: "aws-global"
deployment_identifier: "%{deployment_group}-%{deployment_type}-%{deployment_label}"

storage_bucket_name: "%{hiera('development_group')}-%{hiera('component')}-%{hiera('deployment_identifier')}"
storage_bucket_encryption: "AES256"

ibe_root_account_id: "111005169881"
ibe_management_account_id: ""
