---
:backends:
  - "overrides"
  - "env"
  - "yaml"
:logger: "noop"
:yaml:
  :datadir: "config"
:hierarchy:
  - "roles/%{role}"
  - "deployments/%{deployment_group}-%{deployment_type}-%{deployment_label}"
  - "pipelines/%{pipeline_type}"
  - "pipelines/defaults"
  - "ci/%{ci_organisation}-%{ci_deployment_type}-%{ci_deployment_label}"
  - "secrets/pipeline/%{ci_organisation}-%{ci_deployment_type}-%{ci_deployment_label}"
  - "defaults"
