---
vars:
  region: "%{hiera('region')}"

  ibe_management_account_email: "%{hiera('ibe_management_account_email')}"
  ibe_parent_account_email: "%{hiera('ibe_parent_account_email')}"
  ibe_development_molybdenum_account_email: "%{hiera('ibe_development_molybdenum_account_email')}"
  ibe_production_holmium_account_email: "%{hiera('ibe_production_holmium_account_email')}"

backend_config:
  bucket: "%{hiera('organization_state_bucket_name')}"
  key: "%{hiera('organization_state_key')}"
  region: "%{hiera('organization_state_bucket_region')}"
  encrypt: "%{hiera('organization_state_bucket_is_encrypted')}"
